"""
Pytest suite for the flu_strain_namer module.

Because the module calls out to `requests`, `host_tools`, `location_tools`,
and reads `package_config` at import/call time, every test mocks those
boundaries. Nothing here hits the network.

Run with:  pytest test_strain_generator.py -v
"""

# NOTE: These test were generated by an LLM. They should be checked carefully.

import sys
from datetime import datetime
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import pytest


# ---------------------------------------------------------------------------
# Import target
# ---------------------------------------------------------------------------
# Adjust this to the real dotted path of the file you posted.
MODULE = "strain_generator.main"


@pytest.fixture
def sm():
    """Import the module fresh so patched package_config is picked up."""
    import importlib
    mod = importlib.import_module(MODULE)
    importlib.reload(mod)
    return mod


@pytest.fixture
def fake_config():
    """A package_config dict shaped the way the code indexes into it."""
    return {
        "COL_dataset_key": "COL2026",
        "COL_version": "1",
        "format": "default",
    }


# ---------------------------------------------------------------------------
# normalize_virus_type  (currently a pass-through)
# ---------------------------------------------------------------------------
class TestNormalizeVirusType:
    def test_type_b(self, sm):
        assert sm.normalize_virus_type("B") == "B"


# ---------------------------------------------------------------------------
# normalize_location
# ---------------------------------------------------------------------------
class TestNormalizeLocation:
    def test_returns_country_and_subdivision_tuple(self, sm):
        # Despite the docstring ("Returns: Normalized location string"),
        # the function actually returns a (country, subdivision) tuple.
        with patch.object(
            sm.location_tools, "get_country_and_subdivision",
            return_value=("US", "US-VA"),
        ) as gcs:
            result = sm.normalize_location("Richmond", "United States")
        assert result == ("US", "US-VA")
        gcs.assert_called_once_with("United States", "Richmond")

    def test_forwards_arguments_in_expected_order(self, sm):
        with patch.object(
            sm.location_tools, "get_country_and_subdivision",
            return_value=("HK", "HK"),
        ) as gcs:
            sm.normalize_location("Hong Kong", "China")
        # country is passed first, location second
        gcs.assert_called_once_with("China", "Hong Kong")


# ---------------------------------------------------------------------------
# make_strain_id
# ---------------------------------------------------------------------------
class TestMakeStrainId:
    def test_id_format(self, sm, fake_config):
        taxon = {"usage_id": "3F72J"}
        with patch.dict(sm.package_config, fake_config, clear=True), \
             patch.object(sm.host_tools, "match_species", return_value=taxon) as ms:
            result = sm.make_strain_id(
                host="Chicken", month="02", sequence="15", lab_id="MN.26A"
            )
        # Format built by the code: {usage_id}.{version}-{sequence}-{lab_id}-{month}
        assert result == "3F72J.1-15-MN.26A-02"
        ms.assert_called_once_with("Chicken", "COL2026")

    def test_uses_dataset_key_from_config(self, sm, fake_config):
        cfg = dict(fake_config, COL_dataset_key="OTHERKEY")
        with patch.dict(sm.package_config, cfg, clear=True), \
             patch.object(sm.host_tools, "match_species",
                          return_value={"usage_id": "X"}) as ms:
            sm.make_strain_id("Duck", "07", "3", "LAB")
        ms.assert_called_once_with("Duck", "OTHERKEY")


# ---------------------------------------------------------------------------
# assemble_strain_name
# ---------------------------------------------------------------------------
class TestAssembleStrainName:
    """
    These tests patch every external touchpoint:
        - requests.Session (context manager)
        - host_tools.scientific_to_vernacular
        - host_tools.match_species
        - location_tools.get_country_and_subdivision
        - package_config
    """

    def _patched(self, sm, fake_config, *, vernacular, subdivision, usage_id="3F72J"):
        """Return a contextmanager stack set up with the given return values."""
        cm = patch.multiple(
            sm.host_tools,
            scientific_to_vernacular=MagicMock(return_value=vernacular),
            match_species=MagicMock(return_value={"usage_id": usage_id}),
        )
        loc = patch.object(
            sm.location_tools, "get_country_and_subdivision",
            return_value=("US", subdivision),
        )
        cfg = patch.dict(sm.package_config, fake_config, clear=True)
        # requests.Session() used as a context manager -> return a dummy
        sess = patch.object(sm.requests, "Session", return_value=_DummySession())
        return cm, loc, cfg, sess

    def test_non_human_host_included(self, sm, fake_config):
        cm, loc, cfg, sess = self._patched(
            sm, fake_config, vernacular="Chicken", subdivision="US-VA"
        )
        with cm, loc, cfg, sess:
            name = sm.assemble_strain_name(
                virus_type="A",
                host="Gallus gallus",
                location="Richmond",
                country="US",
                sequence="02",
                lab_id="MN.26A",
                collection_date=datetime(2026, 2, 15),
            )
        assert name == "A/Chicken/US-VA/3F72J.1-02-MN.26A-02/2026"

    def test_human_host_dropped(self, sm, fake_config):
        cm, loc, cfg, sess = self._patched(
            sm, fake_config, vernacular="Human", subdivision="US-NY"
        )
        with cm, loc, cfg, sess:
            name = sm.assemble_strain_name(
                virus_type="H1N1",
                host="Human",
                location="New York",
                country="US",
                sequence="042",
                lab_id="NYSDOH",
                collection_date=datetime(2026, 11, 3),
            )
        # No host segment for human samples
        assert name == "H1N1/US-NY/3F72J.1-042-NYSDOH-11/2026"

    def test_month_zero_padded(self, sm, fake_config):
        cm, loc, cfg, sess = self._patched(
            sm, fake_config, vernacular="Swine", subdivision="US-IA"
        )
        with cm, loc, cfg, sess:
            name = sm.assemble_strain_name(
                virus_type="H3N2",
                host="Sus scrofa",
                location="Ames",
                country="US",
                sequence="9",
                lab_id="LAB",
                collection_date=datetime(2026, 1, 5),  # month 1 -> "01"
            )
        assert "-01/2026" in name

    def test_empty_subdivision_segment_dropped(self, sm, fake_config):
        # If the location tool yields an empty subdivision string, that
        # component is filtered out by the `if c` comprehension.
        cm, loc, cfg, sess = self._patched(
            sm, fake_config, vernacular="Chicken", subdivision=""
        )
        with cm, loc, cfg, sess:
            name = sm.assemble_strain_name(
                virus_type="A",
                host="Gallus gallus",
                location="Nowhere",
                country="US",
                sequence="1",
                lab_id="LAB",
                collection_date=datetime(2026, 6, 1),
            )
        parts = name.split("/")
        assert "" not in parts
        assert parts[0] == "A"
        assert parts[1] == "Chicken"

    def test_none_vernacular_should_be_treated_as_human(self, sm, fake_config):
        cm, loc, cfg, sess = self._patched(
            sm, fake_config, vernacular=None, subdivision="US-VA"
        )
        with cm, loc, cfg, sess:
            name = sm.assemble_strain_name(
                virus_type="A",
                host="Unknown",
                location="Richmond",
                country="US",
                sequence="1",
                lab_id="LAB",
                collection_date=datetime(2026, 2, 1),
            )
        # Intended behavior: no host segment.
        assert name.startswith("A/US-VA/")

    def test_scientific_to_vernacular_called_with_session(self, sm, fake_config):
        s2v = MagicMock(return_value="Chicken")
        loc = patch.object(
            sm.location_tools, "get_country_and_subdivision",
            return_value=("US", "US-VA"),
        )
        cfg = patch.dict(sm.package_config, fake_config, clear=True)
        dummy = _DummySession()
        with patch.object(sm.host_tools, "scientific_to_vernacular", s2v), \
             patch.object(sm.host_tools, "match_species",
                          return_value={"usage_id": "X"}), \
             loc, cfg, \
             patch.object(sm.requests, "Session", return_value=dummy):
            sm.assemble_strain_name(
                virus_type="A",
                host="Gallus gallus",
                location="Richmond",
                country="US",
                sequence="1",
                lab_id="LAB",
                collection_date=datetime(2026, 2, 1),
            )
        # host passed positionally, session passed as keyword
        args, kwargs = s2v.call_args
        assert args[0] == "Gallus gallus"
        assert kwargs["session"] is dummy


# ---------------------------------------------------------------------------
# CLI: parse_args / run_single / run_file
# ---------------------------------------------------------------------------
class TestParseArgs:
    def test_single_mode_parses_required(self, sm, monkeypatch):
        argv = [
            "strain-gen", "single",
            "-v", "H1N1",
            "--human",
            "-l", "New York",
            "-c", "US",
            "-n", "042",
            "-b", "NYSDOH",
            "-d", "2026-11-03",
        ]
        monkeypatch.setattr(sys, "argv", argv)
        args = sm.parse_args()
        assert args.mode == "single"
        assert args.virus_type == "H1N1"
        assert args.human is True
        assert args.date == "2026-11-03"

    def test_file_mode_defaults(self, sm, monkeypatch):
        argv = ["strain-gen", "file", "-i", "in.csv"]
        monkeypatch.setattr(sys, "argv", argv)
        args = sm.parse_args()
        assert args.mode == "file"
        assert args.input == "in.csv"
        assert args.output is None
        assert args.strain_column == "strain_name"

    def test_missing_mode_exits(self, sm, monkeypatch):
        monkeypatch.setattr(sys, "argv", ["strain-gen"])
        with pytest.raises(SystemExit):
            sm.parse_args()

    def test_single_missing_required_exits(self, sm, monkeypatch):
        # missing --date
        argv = ["strain-gen", "single", "-v", "H1N1", "--human",
                "-l", "NY", "-c", "US", "-n", "1", "-b", "LAB"]
        monkeypatch.setattr(sys, "argv", argv)
        with pytest.raises(SystemExit):
            sm.parse_args()


class TestRunSingle:
    def _args(self, **over):
        base = dict(
            human=True, host=None, virus_type="H1N1", location="NY",
            country="US", sequence="1", lab_id="LAB", date="2026-02-15",
        )
        base.update(over)
        return SimpleNamespace(**base)

    def test_requires_host_or_human(self, sm):
        args = self._args(human=False, host=None)
        with pytest.raises(SystemExit) as exc:
            sm.run_single(args)
        assert "--host is required" in str(exc.value)

    def test_bad_date_format_exits(self, sm):
        args = self._args(date="15-02-2026")
        with pytest.raises(SystemExit) as exc:
            sm.run_single(args)
        assert "YYYY-MM-DD" in str(exc.value)

    def test_calls_assemble_and_prints(self, sm, capsys):
        args = self._args()
        with patch.object(sm, "assemble_strain_name",
                          return_value="A/US-NY/ID/2026") as asm:
            sm.run_single(args)
        out = capsys.readouterr().out.strip()
        assert out == "A/US-NY/ID/2026"
        # human=True -> host forwarded as "Human"
        assert asm.call_args.kwargs["host"] == "Human"
        assert isinstance(asm.call_args.kwargs["collection_date"], datetime)

    def test_host_forwarded_when_not_human(self, sm, capsys):
        args = self._args(human=False, host="Avian")
        with patch.object(sm, "assemble_strain_name", return_value="X") as asm:
            sm.run_single(args)
        assert asm.call_args.kwargs["host"] == "Avian"


class TestRunFile:
    def _args(self, **over):
        base = dict(input="in.csv", output=None, strain_column="strain_name")
        base.update(over)
        return SimpleNamespace(**base)

    def test_defaults_output_to_input(self, sm, capsys):
        args = self._args()
        with patch.object(sm, "process_csv", return_value=(3, [])) as pc:
            sm.run_file(args)
        assert pc.call_args.kwargs["output_path"] == "in.csv"
        err = capsys.readouterr().err
        assert "Wrote 3 strain name(s) to in.csv" in err

    def test_uses_explicit_output(self, sm, capsys):
        args = self._args(output="out.csv")
        with patch.object(sm, "process_csv", return_value=(2, [])) as pc:
            sm.run_file(args)
        assert pc.call_args.kwargs["output_path"] == "out.csv"

    def test_reports_skipped_rows(self, sm, capsys):
        args = self._args()
        errors = [(4, "missing country"), (7, "bad date")]
        with patch.object(sm, "process_csv", return_value=(1, errors)):
            sm.run_file(args)
        err = capsys.readouterr().err
        assert "Skipped 2 row(s)" in err
        assert "Row 4: missing country" in err
        assert "Row 7: bad date" in err

    def test_file_not_found_exits(self, sm):
        args = self._args()
        with patch.object(sm, "process_csv", side_effect=FileNotFoundError("nope")):
            with pytest.raises(SystemExit) as exc:
                sm.run_file(args)
        assert "nope" in str(exc.value)

    def test_value_error_exits(self, sm):
        args = self._args()
        with patch.object(sm, "process_csv",
                          side_effect=ValueError("missing columns")):
            with pytest.raises(SystemExit) as exc:
                sm.run_file(args)
        assert "missing columns" in str(exc.value)


class TestMain:
    def test_dispatches_single(self, sm, monkeypatch):
        monkeypatch.setattr(sm, "parse_args",
                            lambda: SimpleNamespace(mode="single"))
        with patch.object(sm, "run_single") as rs, \
             patch.object(sm, "run_file") as rf:
            sm.main()
        rs.assert_called_once()
        rf.assert_not_called()

    def test_dispatches_file(self, sm, monkeypatch):
        monkeypatch.setattr(sm, "parse_args",
                            lambda: SimpleNamespace(mode="file"))
        with patch.object(sm, "run_single") as rs, \
             patch.object(sm, "run_file") as rf:
            sm.main()
        rf.assert_called_once()
        rs.assert_not_called()


# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------
class _DummySession:
    """Stand-in for requests.Session() used as a context manager."""
    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False
